### ISSUE TITLE
Problem loading module with multisites in JOOMLA 4 and SEBLOD 4.3.0.

### ISSUE THREAD

**Issue by villamizarvic** [Octopoos/SEBLOD.com#6]
Hello, I've installed SEBLOD on a JOOMLA 4 platform. I've created two multisites for this JOOMLA installation:

https://victor.ingeweb.com.co (Main)
https://victorpersona.ingeweb.com.co (persona)
https://victorempresa.ingeweb.com.co (empresa)

I have created two custom HTML modules assigned to the home page of the site, one with access level "persona" and the other with access level "empresa."

When I try to access "persona" the module doesn't appear the first time the page loads, but it does appear the second time. The same issue occurs with "empresa"

Once it's cached, the issue doesn't happen again. However, if I delete the cookies or repeat the steps using the browser's incognito mode, the problem occurs again.

This only happens with Joomla modules, it does not happen with article items, menus and other components.

How can I resolve this issue??..

**Comment by sebastienheraud** [comment]
Hi @villamizarvic,

This issue should be fixed with the latest SEBLOD 4.3.1 release.

Thanks,  
Sebastien
